import os
import time

from dotenv import load_dotenv
from google import genai
from google.genai import types

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    raise RuntimeError("GEMINI_API_KEY is missing from .env")

client = genai.Client(api_key=GEMINI_API_KEY)
print("GEMINI KEY LOADED:", bool(GEMINI_API_KEY))
print("GEMINI KEY PREFIX:", GEMINI_API_KEY[:8] if GEMINI_API_KEY else "NONE")


def ask_gemini(question: str, fact_check_context: str = "", retries: int = 5) -> dict:

    prompt = f"""
You are the AI assistant inside NewsVeil, a news credibility
and fact-checking application.

Your job is to explain the results already generated by NewsVeil.

Rules:
1. Answer the user's question directly and clearly.
2. Use the provided NewsVeil analysis as the main source of information.
3. Do not invent scores, evidence, sources, or search results.
4. Do not claim that you performed a web search unless search results
   are actually included in the context.
5. If the context does not contain enough information, say so clearly.
6. Explain credibility scores and technical results in simple language.
7. Remember that NewsVeil's credibility score is an application-generated
   score based on its defined criteria. It is not an absolute measurement
   of whether information is true.
8. Keep the answer concise but useful.

NEWSVEIL ANALYSIS:
{fact_check_context}

USER QUESTION:
{question}
"""

    for attempt in range(retries):
        try:
            response = client.models.generate_content(
                model="gemini-3.1-flash-lite",
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.3,
                    max_output_tokens=500,
                ),
            )
            return {"success": True, "answer": response.text}
        except Exception as error:
            print(f"GEMINI attempt {attempt+1} failed:", repr(error))
            if attempt < retries - 1:
                time.sleep(3 * (attempt + 1))  # 3s, 6s, 9s, 12s...
            else:
                return {
                    "success": False,
                    "answer": "Sorry, I couldn't process your question right now.",
                    "error": str(error),
                }